# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggingStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Worker')),
            ],
        ),
        migrations.RemoveField(
            model_name='loggingsteps',
            name='worker',
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='project',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='LoggingSteps',
        ),
    ]
