# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20170825_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='comment',
        ),
        migrations.AddField(
            model_name='loggingstep',
            name='details',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loggingstep',
            name='project',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loggingstep',
            name='time_spent',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='details',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='workers',
            field=models.ManyToManyField(blank=True, default=None, to='bot.Worker'),
        ),
    ]
